-- Generated from the old public Ajwa Academy content.
-- Images keep using their existing public URLs and embedded data URIs.

create extension if not exists pgcrypto;

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text,
  category text,
  level text,
  description text,
  image text,
  thumbnail text,
  price numeric,
  original_price numeric,
  duration text,
  lesson_count integer,
  rating numeric,
  reviews_count integer,
  enrolled_students integer,
  instructor_name text,
  instructor_avatar text,
  tags jsonb not null default '[]'::jsonb,
  features jsonb not null default '[]'::jsonb,
  curriculum jsonb not null default '[]'::jsonb,
  outline text,
  progress_enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists courses_slug_key on public.courses (slug);

alter table public.courses enable row level security;

do $$
begin
  create policy "Public read courses"
  on public.courses
  for select
  to anon, authenticated
  using (true);
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create policy "Authenticated write courses"
  on public.courses
  for all
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
exception
  when duplicate_object then null;
end $$;

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text,
  slug text,
  excerpt text,
  content text,
  image text,
  category text,
  author text,
  author_avatar text,
  read_time text,
  views integer not null default 0,
  likes integer not null default 0,
  tags jsonb not null default '[]'::jsonb,
  content_blocks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists blog_posts_slug_key on public.blog_posts (slug);

alter table public.blog_posts enable row level security;

do $$
begin
  create policy "Public read blog posts"
  on public.blog_posts
  for select
  to anon, authenticated
  using (true);
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create policy "Authenticated write blog posts"
  on public.blog_posts
  for all
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
exception
  when duplicate_object then null;
end $$;

create table if not exists public.library_items (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  type text,
  author text,
  description text,
  image text,
  file_url text,
  created_at timestamptz not null default now()
);

alter table public.library_items enable row level security;

do $$
begin
  create policy "Public read library items"
  on public.library_items
  for select
  to anon, authenticated
  using (true);
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create policy "Authenticated write library items"
  on public.library_items
  for all
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
exception
  when duplicate_object then null;
end $$;
