-- Complete Database Schema for Ajwa Online Academy
create extension if not exists pgcrypto;

-- 1. PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  name text,
  role text default 'student',
  is_admin boolean default false,
  avatar_url text,
  phone text,
  whatsapp text,
  country text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

do $$ begin
  create policy "Public read profiles" on public.profiles for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users update own profile" on public.profiles for update to authenticated using (auth.uid() = id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
exception when duplicate_object then null; end $$;

-- 2. COURSES TABLE
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text,
  category text,
  level text,
  description text,
  image text,
  thumbnail text,
  price numeric,
  original_price numeric,
  duration text,
  lesson_count integer default 0,
  rating numeric default 5.0,
  reviews_count integer default 0,
  enrolled_students integer default 0,
  instructor_name text,
  instructor_avatar text,
  tags jsonb not null default '[]'::jsonb,
  features jsonb not null default '[]'::jsonb,
  curriculum jsonb not null default '[]'::jsonb,
  outline text,
  progress_enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists courses_slug_key on public.courses (slug);
alter table public.courses enable row level security;

do $$ begin
  create policy "Public read courses" on public.courses for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated all courses" on public.courses for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 3. LESSONS TABLE
create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade,
  title text not null,
  slug text,
  description text,
  content text,
  video_url text,
  duration text,
  order_index integer default 0,
  is_preview boolean default false,
  created_at timestamptz not null default now()
);

alter table public.lessons enable row level security;

do $$ begin
  create policy "Public read lessons" on public.lessons for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated all lessons" on public.lessons for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 4. ENROLLMENTS TABLE
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  status text default 'active',
  progress numeric default 0,
  created_at timestamptz not null default now()
);

alter table public.enrollments enable row level security;

do $$ begin
  create policy "Public read enrollments" on public.enrollments for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated all enrollments" on public.enrollments for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 5. TRIAL REQUESTS TABLE
create table if not exists public.trial_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  course_id bigint,
  course_title text,
  name text not null,
  email text not null,
  whatsapp text not null,
  country text default 'Not specified',
  timezone text default 'UTC',
  message text,
  status text default 'pending',
  image_url text,
  video_url text,
  created_at timestamptz not null default now()
);

alter table public.trial_requests enable row level security;

do $$ begin
  create policy "Anon insert trial_requests" on public.trial_requests for insert to anon, authenticated with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public read trial_requests" on public.trial_requests for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated write trial_requests" on public.trial_requests for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 6. TRIAL ACCESS TABLE
create table if not exists public.trial_access (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  course_id bigint,
  status text default 'active',
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.trial_access enable row level security;

do $$ begin
  create policy "Public read trial_access" on public.trial_access for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated all trial_access" on public.trial_access for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 7. PAYMENT REQUESTS TABLE
create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  course_id bigint,
  amount text,
  transaction_id text,
  slip_url text,
  note text,
  name text,
  email text,
  whatsapp text,
  status text default 'pending',
  created_at timestamptz not null default now()
);

alter table public.payment_requests enable row level security;

do $$ begin
  create policy "Anon insert payment_requests" on public.payment_requests for insert to anon, authenticated with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public read payment_requests" on public.payment_requests for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated write payment_requests" on public.payment_requests for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 8. BLOG POSTS TABLE
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text,
  slug text,
  excerpt text,
  content text,
  image text,
  category text,
  author text,
  author_avatar text,
  read_time text,
  views integer not null default 0,
  likes integer not null default 0,
  tags jsonb not null default '[]'::jsonb,
  content_blocks jsonb not null default '[]'::jsonb,
  status text default 'published',
  created_at timestamptz not null default now()
);

create unique index if not exists blog_posts_slug_key on public.blog_posts (slug);
alter table public.blog_posts enable row level security;

do $$ begin
  create policy "Public read blog_posts" on public.blog_posts for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated all blog_posts" on public.blog_posts for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 9. LIBRARY ITEMS TABLE
create table if not exists public.library_items (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  type text,
  author text,
  description text,
  image text,
  file_url text,
  created_at timestamptz not null default now()
);

alter table public.library_items enable row level security;

do $$ begin
  create policy "Public read library_items" on public.library_items for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated all library_items" on public.library_items for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 10. ADMINS TABLE
create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  email text not null,
  role text default 'admin',
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;

do $$ begin
  create policy "Public read admins" on public.admins for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated all admins" on public.admins for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
